pipeline {
    agent any

    environment {
        VENV_DIR = '.venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/GemmechuBekele/alx-backend-python.git'
                // ✅ Show current branch (requirement)
                sh 'git branch'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    python3 -m pip install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV_DIR}/bin/activate
                    pytest messaging_app/tests --junitxml=test-results/report.xml
                '''
            }
        }

        stage('Publish Test Report') {
            post {
                always {
                    junit 'test-results/report.xml'
                }
            }
        }
    }
}
