pipeline {
    agent any

    environment {
        VENV_DIR = '.venv'
        IMAGE_NAME = 'gemmechu/messaging_app' // replace with your Docker Hub repo
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/GemmechuBekele/alx-backend-python.git'
            }
        }

        stage('Set up Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV_DIR}/bin/activate
                    pytest messaging_app/tests --junitxml=test-results/report.xml
                '''
            }
        }

        stage('Publish Test Report') {
            post {
                always {
                    junit 'test-results/report.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh """
                        docker build -t ${IMAGE_NAME}:latest messaging_app/
                    """
                }
            }
        }

        stage('Login to Docker Hub and Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${IMAGE_NAME}:latest
                    '''
                }
            }
        }
    }
}

