# Generated by Django 5.2.2 on 2025-06-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
